export EDITOR="nvim"
export VISUAL="nvim"
export SYSTEMD_EDITOR="vim"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/snap/bin:$PATH"
export FZF_CTRL_T_OPTS="--preview 'batcat --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza -T --color=always {} | head -200'"
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/*' --glob '!.cache/*' --glob '!.cargo/*' --glob '!.config/*' --glob '!node_modules/*' --glob '!vendor/*'"