#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define NO_ALT_REPEAT_KEY
#define MIN_LAYERS  FN3
#define MAX_LAYERS  FN8
#define LAYER_RANGE (MAX_LAYERS - MIN_LAYERS + 1)

#define KC_ALPHA    UP(G_alpha, G_ALPHA)     // α / Α
#define KC_BETA     UP(G_beta, G_BETA)       // β / Β
#define KC_GAMMA    UP(G_gamma, G_GAMMA)     // γ / Γ
#define KC_DELTA    UP(G_delta, G_DELTA)     // δ / Δ
#define KC_EPSILON  UP(G_epsilon, G_EPSILON) // ε / Ε
#define KC_ZETA     UP(G_zeta, G_ZETA)       // ζ / Ζ
#define KC_ETA      UP(G_eta, G_ETA)         // η / Η
#define KC_THETA    UP(G_theta, G_THETA)     // θ / Θ
#define KC_IOTA     UP(G_iota, G_IOTA)       // ι / Ι
#define KC_KAPPA    UP(G_kappa, G_KAPPA)     // κ / Κ
#define KC_LAMBDA   UP(G_lambda, G_LAMBDA)   // λ / Λ
#define KC_MU       UP(G_mu, G_MU)           // μ / Μ
#define KC_NU       UP(G_nu, G_NU)           // ν / Ν
#define KC_XI       UP(G_xi, G_XI)           // ξ / Ξ
#define KC_OMICRON  UP(G_omicron, G_OMICRON) // ο / Ο
#define KC_PI       UP(G_pi, G_PI)           // π / Π
#define KC_RHO      UP(G_rho, G_RHO)         // ρ / Ρ
#define KC_SIGMA    UP(G_sigma, G_SIGMA)     // σ / Σ
#define KC_TAU      UP(G_tau, G_TAU)         // τ / Τ
#define KC_UPSILON  UP(G_upsilon, G_UPSILON) // υ / Υ
#define KC_PHI      UP(G_phi, G_PHI)         // φ / Φ
#define KC_CHI      UP(G_chi, G_CHI)         // χ / Χ
#define KC_PSI      UP(G_psi, G_PSI)         // ψ / Ψ
#define KC_OMEGA    UP(G_omega, G_OMEGA)     // ω / Ω

void keyboard_post_init_user(void);
void update_led_colors(void);
layer_state_t layer_state_set_user(layer_state_t state);
bool led_update_user(led_t leds);

enum custom_keycodes {
    CLEAR_LAYER = SAFE_RANGE,
    LAYER_UP,
    LAYER_DOWN,
    V_WORD,
    V_LINE,
    LAYER_4,
    LAYER_5,
    LAYER_6,
    LAYER_7,
    LAYER_8,
};

enum key_layers {
    BASE,
    FN1,
    FN2,
    FN3,
    FN4,
    FN5,
    FN6,
    FN7,
    FN8,
    FN9,
    FN10,
};

enum greek_letters {
    G_ALPHA = 0x0391, // Α
    G_BETA,           // Β
    G_GAMMA,          // Γ
    G_DELTA,          // Δ
    G_EPSILON,        // Ε
    G_ZETA,           // Ζ
    G_ETA,            // Η
    G_THETA,          // Θ
    G_IOTA,           // Ι
    G_KAPPA,          // Κ
    G_LAMBDA,         // Λ
    G_MU,             // Μ
    G_NU,             // Ν
    G_XI,             // Ξ
    G_OMICRON,        // Ο
    G_PI,             // Π
    G_RHO,            // Ρ
    G_SIGMA,          // Σ
    G_TAU,            // Τ
    G_UPSILON,        // Υ
    G_PHI,            // Φ
    G_CHI,            // Χ
    G_PSI,            // Ψ
    G_OMEGA,          // Ω

    G_alpha = 0x03B1, // α
    G_beta,           // β
    G_gamma,          // γ
    G_delta,          // δ
    G_epsilon,        // ε
    G_zeta,           // ζ
    G_eta,            // η
    G_theta,          // θ
    G_iota,           // ι
    G_kappa,          // κ
    G_lambda,         // λ
    G_mu,             // μ
    G_nu,             // ν
    G_xi,             // ξ
    G_omicron,        // ο
    G_pi,             // π
    G_rho,            // ρ
    G_sigma,          // σ
    G_tau,            // τ
    G_upsilon,        // υ
    G_phi,            // φ
    G_chi,            // χ
    G_psi,            // ψ
    G_omega           // ω
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (!record->event.pressed) {
        return true;
    }
    switch (keycode) {
    case CLEAR_LAYER:
        layer_clear();
        layer_on(BASE);
        return false;
    case LAYER_DOWN:
    case LAYER_UP:
        uint8_t current_layer = get_highest_layer(layer_state);
        layer_clear();
        if (keycode == LAYER_UP) {
            if (current_layer < MIN_LAYERS || current_layer >= MAX_LAYERS) {
                layer_on(MIN_LAYERS);
                return false;
            }
            layer_on(current_layer + 1);
            return false;
        }
        if (current_layer <= MIN_LAYERS || current_layer > MAX_LAYERS) {
            layer_on(MAX_LAYERS);
            return false;
        }
        layer_on(current_layer - 1);
        return false;
    case V_WORD:
        SEND_STRING(SS_LCTL(SS_TAP(X_LEFT)));
        SEND_STRING(SS_LCTL(SS_LSFT(SS_TAP(X_RGHT))));
        return false;
    case V_LINE:
        SEND_STRING(SS_LCTL(SS_TAP(X_HOME)));
        SEND_STRING(SS_LCTL(SS_LSFT(SS_TAP(X_END))));
        return false;
    case LAYER_4:
        layer_clear();
        layer_on(4);
        return false;
    case LAYER_5:
        layer_clear();
        layer_on(5);
        return false;
    case LAYER_6:
        layer_clear();
        layer_on(6);
        return false;
    case LAYER_7:
        layer_clear();
        layer_on(7);
        return false;
    case LAYER_8:
        layer_clear();
        layer_on(8);
        return false;
    }

    return true;
}

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [BASE] = LAYOUT_60_ansi(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC,
                         LT(2, KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS,
                         TT(1), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT,
                         KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_UP),
                         KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, TT(3), RALT_T(KC_LEFT), MT(KC_APP, KC_DOWN), RCTL_T(KC_RGHT)),

    [FN1] = LAYOUT_60_ansi(KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_F13,
                         RCS(KC_TAB), LSFT(KC_HOME), LSFT(KC_END), V_WORD, V_LINE, KC_TRNS, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, KC_TRNS, KC_HOME, KC_END, KC_PSCR,
                         TG(1), KC_HOME, KC_END, KC_DEL, KC_BSPC, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_PGUP, KC_PGDN, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, LCTL(KC_C), LCTL(KC_V), KC_TRNS, KC_ENT, KC_TRNS, KC_TRNS, KC_INS, KC_DEL, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, MS_BTN1, CLEAR_LAYER, KC_TRNS, KC_APP, KC_TRNS),

    [FN2] = LAYOUT_60_ansi(QK_REP, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_TRNS,
                         KC_TRNS, KC_GRV, LSFT(KC_SCLN), KC_LBRC, KC_RBRC, KC_EQL, LSFT(KC_8), KC_7, KC_8, KC_9, KC_MINS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, LSFT(KC_6), LSFT(KC_4), LSFT(KC_9), LSFT(KC_0), KC_BSLS, KC_SLSH, KC_4, KC_5, KC_6, LSFT(KC_EQL), KC_TRNS, KC_TRNS,
                         KC_TRNS, LSFT(KC_LBRC), LSFT(KC_RBRC), LSFT(KC_COMM), LSFT(KC_DOT), KC_SCLN, KC_0, KC_1, KC_2, KC_3, LSFT(KC_3), KC_TRNS,
                         KC_LSFT, KC_TRNS, KC_TRNS, KC_LSFT, CLEAR_LAYER, KC_TRNS, KC_TRNS, KC_TRNS),

    [FN3] = LAYOUT_60_ansi(KC_TRNS, KC_AP2_BT1, KC_AP2_BT2, KC_TRNS, LAYER_4, LAYER_5, LAYER_6, LAYER_7, LAYER_8, KC_TRNS, KC_AP_LED_TOG, KC_VOLD, KC_VOLU, KC_MUTE,
                         KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BRID, KC_BRIU, KC_AP_LED_SPEED, KC_AP_LED_NEXT_INTENSITY, KC_MSTP,
                         KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_PGUP, KC_PGDN, KC_MPLY,
                         KC_TRNS, KC_AP2_BT3, KC_AP2_BT4, KC_AP2_BT_UNPAIR, KC_TRNS, LCAG(KC_L), MEH(KC_N), MEH(KC_M), KC_AP_LED_PREV_PROFILE, KC_AP_LED_NEXT_PROFILE, KC_DEL, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),

    [FN4] = LAYOUT_60_ansi(KC_TRNS, KC_NUM, KC_KP_SLASH, KC_KP_ASTERISK, KC_KP_MINUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_KP_7, KC_KP_8, KC_KP_9, KC_KP_PLUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_CAPS, KC_KP_4, KC_KP_5, KC_KP_6, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_KP_0, KC_KP_1, KC_KP_2, KC_KP_3, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_KP_DOT, KC_KP_ENTER, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),

    [FN5] = LAYOUT_60_ansi(KC_TRNS, MS_ACL0, MS_ACL0, MS_ACL2, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, MS_WHLL, MS_UP, MS_WHLR, MS_WHLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, MS_LEFT, MS_DOWN, MS_RGHT, MS_WHLD, KC_TRNS, KC_TRNS, MS_BTN1, MS_BTN2, MS_BTN3, MS_BTN4, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, MS_BTN1, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),

    [FN6] = LAYOUT_60_ansi(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MEH(KC_M),
                         KC_TAB, KC_G, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_U, KC_I, KC_O, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_LSFT, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_J, KC_K, KC_L, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_LCTL, KC_TRNS, KC_LALT, KC_SPACE, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),

    [FN7] = LAYOUT_60_ansi(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),

    [FN8] = LAYOUT_60_ansi(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                         KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, CLEAR_LAYER, LAYER_DOWN, LAYER_UP, KC_TRNS),
};
// clang-format on

void keyboard_post_init_user(void) {
    ap2_led_enable();
    ap2_led_set_profile(3);
}

void update_led_colors(void) {
    ap2_led_reset_foreground_color();
    const ap2_led_t color_yellow = {.p.red = 0xff, .p.green = 0xff, .p.blue = 0x00, .p.alpha = 0xff};
    const ap2_led_t color_red    = {.p.red = 0xff, .p.green = 0x00, .p.blue = 0x00, .p.alpha = 0xff};
    // Set number key to yellow
    for (size_t col = 1; col < 13; col++) {
        ap2_led_colors_set_key(0, col, color_yellow);
    }
    for (size_t col = 1; col < 13; col++) {
        ap2_led_colors_set_key(1, col, color_red);
    }
    for (size_t col = 1; col < 12; col++) {
        ap2_led_colors_set_key(2, col, color_red);
    }
    for (size_t col = 1; col < 11; col++) {
        ap2_led_colors_set_key(3, col, color_red);
    }
}

layer_state_t layer_state_set_user(layer_state_t state) {
    switch (get_highest_layer(state)) {
    // case BASE:
    //     update_led_colors();
    //     break;
    case FN3:
        ap2_led_set_foreground_color(0xFF, 0x00, 0x00);
        break;
    case FN4:
        ap2_led_set_foreground_color(0xFF, 0x80, 0x00);
        break;
    case FN5:
        ap2_led_set_foreground_color(0xFF, 0xFF, 0x00);
        break;
    case FN6:
        ap2_led_set_foreground_color(0x80, 0xFF, 0x00);
        break;
    case FN7:
        ap2_led_set_foreground_color(0x00, 0xFF, 0x00);
        break;
    case FN8:
        ap2_led_set_foreground_color(0x00, 0xFF, 0xFF);
        break;
    case FN9:
        ap2_led_set_foreground_color(0x00, 0x00, 0xFF);
        break;
    case FN10:
        ap2_led_set_foreground_color(0x80, 0x00, 0xFF);
        break;
    default:
        // Reset back to the current profile
        ap2_led_reset_foreground_color();
        break;
    }
    return state;
}

// The function to handle the caps lock logic
// It's called after the capslock changes state or after entering layers 1 and 2.
bool led_update_user(led_t leds) {
    if (leds.caps_lock) {
        // Set the caps-lock to red
        const ap2_led_t color = {.p.red = 0xff, .p.green = 0x00, .p.blue = 0x00, .p.alpha = 0xff};
        ap2_led_sticky_set_key(2, 0, color);
        /* NOTE: Instead of colouring the capslock only, you can change the whole
           keyboard with ap2_led_mask_set_mono */
    } else {
        // Reset the capslock if there is no layer active
        ap2_led_unset_sticky_key(2, 0);
    }

    return true;
}

#ifdef OTHER_KEYMAP_C
#include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
