services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    ports:
      - '3001:80'
      - '3003:443'
      - '3002:22'
    volumes:
      - '/home/imotfnir/docker/gitlab/config:/etc/gitlab'
      - '/home/imotfnir/docker/gitlab/logs:/var/log/gitlab'
      - '/home/imotfnir/docker/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
