services:
  dashy:
    image: "lissy93/dashy:latest"
    container_name: "dashy"
    restart: always
    volumes:
      - ./dashy/conf.yml:/app/user-data/conf.yml
      - ${DATA_DIR}/dashy:/app/user-data
    ports:
      - 17054:8080
    environment:
      - NODE_ENV=production
      - HOST_IP="192.168.0.253"
      - HOSTNAME="n100.local"

  beszel:
    image: "henrygd/beszel:latest"
    container_name: "beszel"
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${DATA_DIR}/beszel_data:/beszel_data

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data

  watchtower:
    image: "containrrr/watchtower:latest"
    container_name: "watchtower"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

