services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ${HOME_DIR}/.acme.sh:/etc/letsencrypt:ro
      - ${DOCKER_DATA_DIR}/nginx:/usr/share/nginx
    restart: unless-stopped

  goaccess:
    image: allinurl/goaccess:latest
    container_name: goaccess
    volumes:
      - ${DOCKER_DATA_DIR}/nginx/logs/:/var/log/nginx/:ro
      - ${DOCKER_DATA_DIR}/goaccess:/data
    environment:
      - LANG=en_US.UTF-8
    ports:
      - 7891:7890
    restart: unless-stopped
    command:
      - "/var/log/nginx/access.log"
      - "-a"
      - "-o report.html"
      - "--log-format=COMBINED"
      - "--real-time-html"
      - "--persist"
      - "--restore"
