services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ${HOME_DIR}/.acme.sh:/etc/letsencrypt:ro
      - ${DATA_DIR}/nginx:/usr/share/nginx
    restart: unless-stopped
