services:
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ${DOCKER_DATA_DIR}/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped
