services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      # - REDIS_URL= #optional
    volumes:
      - ${DOCKER_DATA_DIR}/paperless-ngx/config:/config
      - ${DOCKER_DATA_DIR}/paperless-ngx/data:/data
    ports:
      - 8000:8000
    restart: unless-stopped
