services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Taipei
      - UMASK=002
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /var/lib/qbittorrent/appdata:/config
      - ${STORAGE_DIR}/qbittorrent:/downloads #optional
      - ${STORAGE_DIR}/qbittorrent_share:/share #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  qbitorrent_share:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_share
    environment:
      - PUID=1000
      - PGID=1003
      - UMASK=002
      - TZ=Asia/Taipei
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6882
    volumes:
      - /var/lib/qbittorrent_share/appdata:/config
      - ${STORAGE_DIR}/qbittorrent_share:/downloads #optional
    ports:
      - 8081:8081
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Asia/Taipei
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${DATA_DIR}/jackett:/config
      - ${STORAGE_DIR}/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
