events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        listen [::]:80;
        server_name home.imotfnir.qzz.io www.imotfnir.qzz.io home.741400.xyz www.741400.xyz;

        location / {
              return 301 https://www.741400.xyz$request_uri;
        }

    }

    server {
        listen 80;
        listen [::]:80;
        server_name n100.local ;

        location / {
              return 301 https://$host$request_uri;
        }

    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name home.imotfnir.qzz.io www.imotfnir.qzz.io home.741400.xyz www.741400.xyz;

        root /usr/share/nginx/html;
        index index.html index.htm;

        ssl_certificate /etc/letsencrypt/741400.xyz_ecc/fullchain.cer;
        ssl_certificate_key /etc/letsencrypt/741400.xyz_ecc/741400.xyz.key;
        include /etc/nginx/ssl_params.conf;
        include /etc/nginx/proxy_params.conf;

        location /.well-known/acme-challenge/ {
            try_files $uri =404;
        }

        location /openspeedtest/ {
            proxy_pass http://127.0.0.1:3000/;
        }

        location /hysteria2/ {
            proxy_pass http://127.0.0.1:60000/;
        }

        location /monitor/ {
            proxy_pass http://127.0.0.1:8090/;
        }

        location /qbittorrent/  {
            proxy_pass http://127.0.0.1:8081/;
        }

        location /jellyfin/ {
            proxy_pass http://127.0.0.1:8096/;
        }

    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name n100.local;
        include /etc/nginx/proxy_params.conf;

        location / {
            proxy_pass http://127.0.0.1:17054/;
        }

        location /openspeedtest/ {
            proxy_pass http://127.0.0.1:3000/;
        }

        location /monitor/ {
            proxy_pass http://127.0.0.1:8090/;
        }

        location /protainer/ {
            proxy_pass http://127.0.0.1:9000/;
        }

        location /qbittorrent/ {
            proxy_pass http://127.0.0.1:8081/;
        }

        location /jackett/ {
            proxy_pass http://127.0.0.1:9117/;
        }

        location /jellyfin/ {
            proxy_pass http://127.0.0.1:8096/;
        }

        location /jellyseerr/ {
            proxy_pass http://127.0.0.1:5055/;
        }

        location /radarr/ {
            proxy_pass http://127.0.0.1:7878/;
        }

        location /sonarr/ {
            proxy_pass http://127.0.0.1:8989/;
        }

        location /hui/ {
            proxy_pass http://127.0.0.1:5001/;
        }

    }
}