ungrouped:
server:
  hosts:
    orangepi:
      ansible_host: 192.168.0.7
      ansible_user: imotfnir
      ansible_ssh_private_key_file: ~/.ssh/orangepi2
      ansible_become_pass: "{{ vault_ansible_become_pass }}"

test:
  hosts:
    ansible-test:
      ansible_connection: docker
