all:
  children:
    homelab:
      hosts:
        orangepi:
          ansible_host: orangepione.local
          ansible_user: imotfnir
          ansible_ssh_private_key_file: ~/.ssh/orangepione
      vars:
        ansible_become_pass: "{{ vault_ansible_become_pass }}"

    debian:
      hosts:
        debian:
          ansible_host: debian.local
          ansible_user: imotfnir
          ansible_ssh_private_key_file: ~/.ssh/debian
      vars:
        ansible_become: true

    cloud:
      hosts:
        vps:
          ansible_host: vps.741400.xyz
          ansible_user: imotfnir
          ansible_ssh_private_key_file: ~/.ssh/google_vps
      vars:
        ansible_become: true

    test:
      hosts:
        ansible-test:
          ansible_connection: docker