ungrouped:
server:
  hosts:
    orangepi:
      ansible_host: 192.168.0.7
      ansible_user: imotfnir
      ansible_ssh_private_key_file: ~/.ssh/orangepi2
      ansible_become_pass: "{{ vault_ansible_become_pass }}"

ansible-test:
  hosts:
    test:
      ansible_host: 172.20.0.2
