- name: System setup
  hosts: test
  vars_files:
    - vars.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
      ignore_errors: yes

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
      become: yes
      register: git_install_result
      ignore_errors: yes

    - name: Install go
      ansible.builtin.package:
        name: golang
        state: present
      become: yes
      register: go_install_result
      ignore_errors: yes

    - name: Install snap
      ansible.builtin.package:
        name:
          - snap
          - snapd
        state: present
      become: yes
      register: snap_install_result
      ignore_errors: yes

    - name: Install basic tools
      ansible.builtin.package:
        name:
          - eza
          - tmux
          - vim
          - htop
          - btop
          - ranger
          - trash-cli
          - wireguard
          - ripgrep
          - tmuxinator
        state: present
      become: yes
      ignore_errors: yes

    - name: Install Miniconda
      ansible.builtin.import_tasks: tasks/conda.yml
      become: no
      ignore_errors: yes
      register: conda_install_result

    - name: Install pip, python
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
      become: yes
      ignore_errors: yes
      register: python_install_result
      when: conda_install_result.failed

    - name: Install go-tools
      ansible.builtin.import_tasks: tasks/go_tools.yml
      become: no
      when: not go_install_result.failed
